### PR TITLE
Fix #2385

### LINKED ISSUE #2385: Tasks associated with removed jobs are still visible from REST resources
If I kill a job and then remove it, its tasks still shows up in the task centric view.

To reproduce (new database, begin in the job-centric view):
1. submit a new job (no particular way)
2. kill the job
3. remove the job
4. switch to the task-centric view, there are still tasks remaining

### PR DESCRIPTION
**Pull request by paraita**
When pa.scheduler.job.removeFromDataBase is set to false (default value), tasks from removed jobs still come up in the task-centric view's task list. A new statement has been added to the existing criterias that fetches only the tasks (jobData.removedTime = -1) whose jobs weren't removed.

### CODE REVIEW

File: scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/db/TaskDBUtils.java [hunk 1]
```diff
@@ -27,6 +27,9 @@
                 Criteria criteria = session.createCriteria(TaskData.class);
                 List<TaskState> result = null;
                 
+                // only fetch non-removed tasks
+                criteria.createAlias("jobData", "job").add(Restrictions.eq("job.removedTime", -1L));
```
Comment (sonarqube-activeeon) [inline scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/db/TaskDBUtils.java]: MINOR Define a constant instead of duplicating this literal "jobData" 4 times. [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1192)

**Comment by sonarqube-activeeon** [comment]
SonarQube analysis reported 9 issues:
* MAJOR 7 major
* MINOR 2 minor

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [The Cyclomatic Complexity of this method "taskStateSessionWork" is 19 which is greater than 10 authorized.](https://github.com/ow2-proactive/scheduling/blob/aa606dbd9e6782f91afb3aeceb61baa605fc29dc/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/db/TaskDBUtils.java#L20) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
* MAJOR [The Cyclomatic Complexity of this method "executeWork" is 17 which is greater than 10 authorized.](https://github.com/ow2-proactive/scheduling/blob/aa606dbd9e6782f91afb3aeceb61baa605fc29dc/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/db/TaskDBUtils.java#L95) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
* MAJOR [Add a private constructor to hide the implicit public one.](https://github.com/ow2-proactive/scheduling/blob/aa606dbd9e6782f91afb3aeceb61baa605fc29dc/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/db/TaskDBUtils.java#L18) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1118)
* MINOR [At most one statement is allowed per line, but 2 statements were found on this line.](https://github.com/ow2-proactive/scheduling/blob/aa606dbd9e6782f91afb3aeceb61baa605fc29dc/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/db/TaskDBUtils.java#L97) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS00122)
* MAJOR [Reduce this anonymous class number of lines from 62 to at most 20, or make it a named class.](https://github.com/ow2-proactive/scheduling/blob/aa606dbd9e6782f91afb3aeceb61baa605fc29dc/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/db/TaskDBUtils.java#L91) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1188)
* MAJOR [Reduce this anonymous class number of lines from 64 to at most 20, or make it a named class.](https://github.com/ow2-proactive/scheduling/blob/aa606dbd9e6782f91afb3aeceb61baa605fc29dc/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/db/TaskDBUtils.java#L22) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1188)
* MAJOR [The Cyclomatic Complexity of this method "executeWork" is 18 which is greater than 10 authorized.](https://github.com/ow2-proactive/scheduling/blob/aa606dbd9e6782f91afb3aeceb61baa605fc29dc/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/db/TaskDBUtils.java#L26) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
* MAJOR [The Cyclomatic Complexity of this method "taskInfoSessionWork" is 18 which is greater than 10 authorized.](https://github.com/ow2-proactive/scheduling/blob/aa606dbd9e6782f91afb3aeceb61baa605fc29dc/scheduler/scheduler-server/src/main/java/org/ow2/proactive/scheduler/core/db/TaskDBUtils.java#L89) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

**Comment by marcocast** [comment]
Could you add some JUnit test?

**Comment by paraita** [comment]
I wrote some system tests for these changes, do you want some unit tests also ?
